app:
  database_path: 'data/database.json'
  crawlers:
    ouest_france: # used for crawler class name: Crawler\Implementation\OuestFranceCrawler
      name: 'Ouest France'
      base_url: 'https://www.ouestfrance-immo.com'
      ad_selector: '#listAnnonces>a'
      urls:
        - 'https://www.ouestfrance-immo.com/louer/maison/nantes-44-44000/?prix=0_1100'
        - 'https://www.ouestfrance-immo.com/louer/maison/reze-44-44400/?prix=0_1100'
        - 'https://www.ouestfrance-immo.com/louer/maison/saint-sebastien-sur-loire-44-44230/?prix=0_1100'
        - 'https://www.ouestfrance-immo.com/immobilier/location/maison/saint-herblain-44-44162/?prix=0_1100'
    se_loger:
      name: 'Se Loger'
      ad_selector: 'div[class*="ListContent__SmartClassifiedExtended"]'
      urls:
        - 'https://www.seloger.com/list.htm?ci=440109,440143,440190&idtt=1&idtypebien=2&pxmax=1100&tri=d_dt_crea'
        - 'https://www.seloger.com/immobilier/locations/immo-saint-herblain-44/?projects=1&types=2&places=[{ci:440162}]&price=NaN/1100&enterprise=0&qsVersion=1.0'
    century_21:
      name: 'Century 21'
      base_url: 'https://www.century21.fr'
      ad_selector: '#blocANNONCES li.annonce'
      urls:
        - 'https://www.century21.fr/annonces/location-maison/v-st+sebastien+sur+loire-reze-st+herblain/cpv-44200_nantes-44100_nantes-44000_nantes-44300_nantes/s-0-/st-0-/b-0-1100/page-1/'
    century_21_saint_sebastien:
      name: 'Century 21 Saint-Sebastien'
      base_url: 'https://www.century21byouestsaintseb.com'
      ad_selector: '#blocANNONCES li.annonce'
      urls:
        - 'https://www.century21byouestsaintseb.com/annonces/location-maison/s-0-/st-0-/b-0-1100/'
    four_immo:
      name: '4 immo'
      base_url: 'https://www.4immo.fr'
      ad_selector: 'article.node'
      urls:
        - 'https://www.4immo.fr/location/maison/nantes?prix_maximum=1100&surface_minimum=60'
        - 'https://www.4immo.fr/location/maison/reze?prix_maximum=1100&surface_minimum=60'
        - 'https://www.4immo.fr/location/maison/st-herblain?prix_maximum=1100&surface_minimum=60'
        - 'https://www.4immo.fr/location/maison/st-sebastien-sur-loire?prix_maximum=1100&surface_minimum=60'
    fnaim:
      name: 'Fnaim'
      base_url: 'https://www.fnaim.fr'
      ad_selector: 'ul.liste li.item'
      urls:
        - 'https://www.fnaim.fr/liste-annonces-immobilieres/18--.htm?TRANSACTION=2&localites=%5B%7B%22id%22%3A8183%2C%22type%22%3A3%2C%22label%22%3A%22NANTES+(44000)%22%2C%22insee%22%3A%2244109%22%7D%2C%7B%22id%22%3A%2234489%22%2C%22type%22%3A%223%22%2C%22label%22%3A%22REZE+(44400)%22%2C%22insee%22%3A%2244143%22%7D%2C%7B%22id%22%3A%227231%22%2C%22type%22%3A%223%22%2C%22label%22%3A%22ST+SEBASTIEN+SUR+LOIRE+(44230)%22%2C%22insee%22%3A%2244190%22%7D%2C%7B%22id%22%3A%2226747%22%2C%22type%22%3A%223%22%2C%22label%22%3A%22ST+HERBLAIN+(44800)%22%2C%22insee%22%3A%2244162%22%7D%5D&TYPE%5B%5D=2&NB_PIECES%5B%5D=&NB_PIECES%5B%5D=&SURFACE%5B%5D=&SURFACE%5B%5D=&PRIX%5B%5D=&PRIX%5B%5D=1100&NB_CHAMBRES%5B%5D=&NB_CHAMBRES%5B%5D=&SURFACE_TERRAIN%5B%5D=&SURFACE_TERRAIN%5B%5D=&op=CEN_VTE_PRIX_VENTE+asc%2CTRI_PRIX+asc%2CCEN_MDT_DTE_CREATION+desc&cp=b5356780a90c44e41dd9&mp=11&lat=47.22236621783472&lng=-1.5758514404296877&zoom=11'
